services:
  mando-hgt-rebuild:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6006:6006
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes: # docker run -v
      - .:/app/mando-hgt
      #- ./hgt:/app/hgt
    working_dir: /app/mando-hgt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true # not stop after build = docker run -t
