services:
  mando-hgt-rebuild:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    volumes:
      - .:/app/mando-hgt
      #- ./hgt:/app/hgt
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm